cd models
node administrador/administrador.js
node cliente/cliente.js
node produtos/produtos.js
node funcionario/funcionario.js
node promocoes/promocoes.js
node carrinho/carrinho.js
node endereco/endereco.js
node compra/compra.js
node entrega/entrega.js
node produtoCompra/produtoCompra.js